import pandas as pd

def generate_api_server_script(
    model_name: str, 
    target: str, 
    problem_type: str, 
    features: list, 
    cat_feats: list, 
    dummy_columns: list,
    cc: dict,
    X_raw: pd.DataFrame
) -> str:
    # Build Pydantic field lines
    _pydantic_fields = []
    for _fc in features:
        if _fc in cat_feats:
            _pydantic_fields.append(f"    {_fc}: str")
        elif _fc in cc.get("numeric", []):
            _col_sample = X_raw[_fc] if _fc in X_raw.columns else pd.Series(dtype=float)
            if pd.api.types.is_integer_dtype(_col_sample):
                _pydantic_fields.append(f"    {_fc}: int")
            else:
                _pydantic_fields.append(f"    {_fc}: float")
        else:
            _pydantic_fields.append(f"    {_fc}: float")
    _pydantic_block = "\n".join(_pydantic_fields)

    # Encoding block
    _enc_lines = [
        "    import pandas as pd",
        "    row = {",
    ]
    for _fc in features:
        _enc_lines.append(f"        '{_fc}': data.{_fc},")
    _enc_lines.append("    }")
    _enc_lines.append("    df_in = pd.DataFrame([row])")
    if cat_feats:
        _enc_lines.append(f"    cat_cols = {cat_feats!r}")
        _enc_lines.append("    df_in = pd.get_dummies(df_in, columns=cat_cols)")
    _enc_lines.append(f"    expected_cols = {dummy_columns!r}")
    _enc_lines.append("    for col in expected_cols:")
    _enc_lines.append("        if col not in df_in.columns:")
    _enc_lines.append("            df_in[col] = 0")
    _enc_lines.append("    df_in = df_in[expected_cols]")
    _encoding_block = "\n".join(_enc_lines)

    if problem_type == "classification":
        _return_block = '    prediction = bundle["model"].predict(df_in)[0]\n    return {"prediction": str(prediction)}'
    else:
        _return_block = '    prediction = bundle["model"].predict(df_in)[0]\n    return {"prediction": float(prediction)}'

    _api_script = f'''"""Auto-generated FastAPI server
Model: {model_name} | Target: {target} | Type: {problem_type}
Generated by DataForge AI
"""
import sys

# Auto-detect missing dependencies
_missing = []
for _mod in ["fastapi", "pydantic", "uvicorn", "pandas", "sklearn"]:
    try:
        __import__(_mod)
    except ImportError:
        _missing.append(_mod if _mod != "sklearn" else "scikit-learn")

if _missing:
    print("\\n❌ ERROR: Missing required dependencies.")
    print("Please run the following command to install them into your current Python environment:\\n")
    print(f"    {{sys.executable}} -m pip install {{' '.join(_missing)}}\\n")
    sys.exit(1)

from fastapi import FastAPI
from pydantic import BaseModel
import pickle
import uvicorn

app = FastAPI(title="DataForge AI Model API", version="1.0.0")

with open("model.pkl", "rb") as f:
    bundle = pickle.load(f)


class InputData(BaseModel):
{_pydantic_block}


@app.get("/health")
def health():
    return {{"status": "ok", "model": bundle.get("best_model_name", "unknown")}}


@app.post("/predict")
def predict(data: InputData):
{_encoding_block}
{_return_block}


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''
    return _api_script
